spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yuri.matteus.1997@gmail.com
    password: ldhbijpjhdhbqfso
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
